services:
  ml_app:
    build: 
      context: ./all-models-mlflow
      dockerfile: Dockerfile
    container_name: ml_app
    volumes:
      - ./mlruns:/app/mlruns
      - ./dados:/app/dados
    environment:
      - MLFLOW_TRACKING_URI=file:/app/mlruns
    command: python videogame.py

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow_ui
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    # depends_on:
    #   - ml_app
    environment:
      - MLFLOW_TRACKING_URI=file:/mlruns
    command: mlflow ui --backend-store-uri /mlruns --host 0.0.0.0 --port 5000
  
  mlflow-best-model:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow_best_model
    ports:
      - "5001:5001"
    # depends_on:
    #   - ml_app
    volumes:
      - ./mlruns:/mlruns
    environment:
      - MLFLOW_TRACKING_URI=file:/mlruns
    # Ajustar parametros para sua Run do MLFLOW
    command: mlflow models serve -m /mlruns/experiment-id/models/model-id/artifacts --no-conda --host 0.0.0.0 --port 5001

  # api-bestmodel-test:
  #   build: .
  #   container_name: best_model_api
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./best_model_api.pkl:/app/best_model_api.pkl
  #   depends_on:
  #     - ml_app
  #   command: mlflow models serve -m /app/mlruns/0/<ID_DO_RUN>/artifacts/MLP_model --host 0.0.0.0 --port 5000

